# Generated by Django 3.2.7 on 2021-12-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255, unique=True)),
                ('campaign_status', models.CharField(max_length=10)),
                ('campaign_date', models.DateField(auto_now_add=True)),
                ('campaign_metric', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('campaign_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(max_length=50)),
                ('global_template_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
                ('user_zip_code', models.CharField(max_length=50)),
                ('user_address', models.TextField()),
                ('campaign_info', models.TextField()),
                ('template_info', models.TextField()),
                ('campaign_list', models.TextField()),
                ('templates', models.TextField()),
                ('global_templates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadList',
            fields=[
                ('upload_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.IntegerField()),
                ('email_opened', models.IntegerField()),
                ('email_bounced', models.IntegerField()),
                ('campaign_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.campaigntemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_version', models.IntegerField(blank=True, default='0')),
                ('message', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('contact_status', models.CharField(max_length=10)),
                ('is_spammer', models.CharField(blank=True, default='N', max_length=1)),
                ('last_time_contact', models.DateField(auto_now_add=True)),
                ('x_time_contact', models.IntegerField()),
                ('activity', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campaigntemplate')),
                ('upload_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campaign')),
                ('global_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.globalcontact')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campaigntemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campaigncontact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
